GET http://127.0.0.1:8080/slots/availability

###
POST http://127.0.0.1:8080/slots/3/hold
Content-Type: application/json
Idempotency-Key: {{$random.uuid}}

###
POST http://127.0.0.1:8080/holds/15/confirm

###
DELETE http://127.0.0.1:8080/holds/1
